### ISSUE TITLE
cloneAction step fails on schema validation on toxiproxy 

### ISSUE THREAD

**Issue by efarrokh** [powerfulseal/powerfulseal#319] opened 2021-02-24 00:17 UTC
Hello. I'm unable to use cloneAction to clone existing deployment for toxiproxy usecase. The issue appears to be in schema validation. I'm using the goldpinger example in minikube to test this tool. 

Partial error reads:

> 2021-02-23 16:06:20 ERROR policy_runner {'config': {'runStrategy': {'runs': 1}}, 'scenarios': [{'name': 'Clone and tc', 'steps': [{'clone': {'source': {'deployment': {'name': 'goldpinger', 'namespace': 'default'}}}}]}]}
2021-02-23 16:06:20 ERROR policy_runner Additional properties are not allowed ('clone' was unexpected)
Failed validating 'additionalProperties' in schema[0]:

> On instance:
    {'clone': {'source': {'deployment': {'name': 'goldpinger',
                                         'namespace': 'default'}}}}
2021-02-23 16:06:20 ERROR __main__ Policy not valid. See log output above.

My completely stripped out action reveals this issue. This was copied from the TC example but the toxiproxy example also has the same issue. 

```
config:
  runStrategy:
    runs: 1
scenarios:
- name: Clone and tc
  steps:
  - clone:
      source:
        deployment:
          name: goldpinger
          namespace: default
```

Would really appreciate your help.

**Comment by efarrokh** [comment] 2021-02-24 01:38
This appears to work when I build from repo instead of using pypi release of 3.1.0

**Comment by seeker89** [comment] 2021-02-24 09:29
Hi, yes, releasing 3.2.0 was blocked due to our issues with Docker Hub. Sorry for the inconvenience, we should be able to get back to that soon...

**Comment by seeker89** [comment] 2021-02-24 09:30
Dupe of https://github.com/powerfulseal/powerfulseal/issues/312

**Comment by rxwang662001** [comment] 2021-03-05 03:03
Hello,

Yes , after building image with the latest code, the policy file with toxiproxy could deploy, but the new created chaos pod goldpinger-chaos-dd4c4fdb8-qz6m9 always not running for container: chaos-toxiproxy.

It reports error:

 Normal   Created    42s        kubelet, node-10-120-127-215  Created container chaos-toxiproxy
  Normal   Started    42s        kubelet, node-10-120-127-215  Started container chaos-toxiproxy
  Warning  Unhealthy  3s         kubelet, node-10-120-127-215  Startup probe failed: Failed to create proxy: Post http://localhost:8474/proxies: dial tcp: i/o timeout

Actually following the example I already set the - targetProxy: 8080
Not sure the port 8474 from in the error.

The example I follow is:

https://powerfulseal.github.io/powerfulseal/network-slowness-with-toxiproxy

Could anyone point out what's the problem?

Thanks,
Ruixia

**Comment by seeker89** [comment] 2021-03-08 18:45
Hmm, that's odd. That startup probe is used to configure ToxiProxy. Could you share the entire experiment yaml you used?

**Comment by rxwang662001** [comment] 2021-03-18 08:46
Thanks seeker89 for your response! and sorry for my delay cause of blocking of other work.
Today I picked this up and tried on another cluster, it looks good this time for the same toxiproxy chaos experiment.
I'll monitor it further to see.
and look forward to the latest build image in docker hub and now I'm using my own build with the latest code.

Thanks again.
Ruixia

**Comment by sathiyajith** [comment] 2021-05-07 04:19
Hi @rxwang662001 and @seeker89 
I also tried the same experiment and getting the schema error.
Im using the bloomberg/goldpingerv3.0.0 image. Should I change the image? If so what image should I use? Please mention the solution.

**Comment by seeker89** [comment] 2021-05-07 05:44
Hey @sathiyajith - you're going to need to build the Docker image for version 3.2.0+ - or just the latest from the master branch.

With the recent changes to the public docker hub repos, we're still unsure where to push the images...

**Comment by sathiyajith** [comment] 2021-05-07 05:52
Are you talking about the powerfulseal image or goldpinger image? Also, I installed powerfulseal through pip. In that case, what should I do? Is there any slack community where we can talk in brief about this?

**Comment by seeker89** [comment] 2021-05-07 06:35
@sathiyajith You didn't mention the version of PowerfulSeal, so I recommend trying to run directly from master on this repo.

**Comment by seeker89** [comment] 2021-05-07 06:36
We don't have a slack channel unfortunately.

**Comment by sathiyajith** [comment] 2021-05-07 07:00
Yeah, Im running powerfulseal-3.1.0. I have upgraded to 3.2.0. 
Now it is running fine.
Thanks @seeker89.  Hoping to work and contribute more on powerfulseal.

**Comment by seeker89** [comment] 2021-05-07 07:06
Awesome!

**Closed by seeker89** 2021-05-07 07:06 UTC
